version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "library"
      POSTGRES_USER: "danis"
      POSTGRES_PASSWORD: "danis"
    ports:
      - "5432:5432"